
location      = "east us 2"
snname        = "default"
vnetname      = "rg10272021-vnet"
rg            = "rg10272021"
vmname        = "TSTVM01"
vmsku         = "2019-Datacenter"
vmsize        = "Standard_B4ms"
adminUsername = "tstadmin"
adminPassword = "ThisIsABadPassw0rd!"